name: LikeC4 Export
description: Export LikeC4 views to png
author: likec4
inputs:
  src:
    description: directory with likec4 sources
    required: false
    default: '.'
  out:
    description: directory for generated png
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.out }}
    - ${{ inputs.src }}    

branding:
  icon: image
  color: gray-dark