name: Export LikeC4 views to png
description: Export LikeC4 views to png, rendering in Headless Chrome
author: likec4
inputs:
  src:
    description: directory with likec4 sources
    required: false
    default: '.'
  output:
    description: directory for generated png
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output }}
    - ${{ inputs.src }}    

branding:
  icon: image
  color: gray-dark